/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TranslateBlockPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/models.ts
var FALLBACK_MODEL = "llama3";
function parseModelList(raw, fallbackModel) {
  const fallback = ((fallbackModel == null ? void 0 : fallbackModel.trim()) || FALLBACK_MODEL).trim();
  const seen = /* @__PURE__ */ new Set();
  const result = [];
  for (const line of (raw != null ? raw : "").split("\n")) {
    const name = line.trim();
    if (!name || seen.has(name)) continue;
    seen.add(name);
    result.push(name);
  }
  if (result.length === 0) {
    return [fallback];
  }
  return result;
}
function resolveModel(list, preferred) {
  const models = list.length > 0 ? list : parseModelList("");
  const want = preferred == null ? void 0 : preferred.trim();
  if (want && models.includes(want)) {
    return want;
  }
  return models[0];
}
function populateModelSelect(select, models, current) {
  const list = models.length > 0 ? models : parseModelList("");
  const selected = resolveModel(list, current);
  select.empty();
  for (const value of list) {
    const opt = select.createEl("option", { value, text: value });
    if (value === selected) {
      opt.selected = true;
    }
  }
}

// src/languages.ts
var LANGUAGE_OPTIONS = ["auto", "en", "zh", "ja", "fr", "de", "es"];
function resolveLanguage(preferred, fallback) {
  const want = preferred == null ? void 0 : preferred.trim();
  if (want && LANGUAGE_OPTIONS.includes(want)) {
    return want;
  }
  if (LANGUAGE_OPTIONS.includes(fallback)) {
    return fallback;
  }
  return LANGUAGE_OPTIONS[0];
}
function populateLanguageSelect(select, current) {
  const selected = resolveLanguage(current, LANGUAGE_OPTIONS[0]);
  select.empty();
  for (const value of LANGUAGE_OPTIONS) {
    const opt = select.createEl("option", { value, text: value });
    if (value === selected) {
      opt.selected = true;
    }
  }
}

// src/settings.ts
var import_obsidian = require("obsidian");
var MIN_POLL_INTERVAL_MS = 500;
var DEFAULT_SETTINGS = {
  endpointUrl: "http://localhost:13434/api/chat",
  modelsRaw: "llama3",
  defaultModel: "llama3",
  defaultPrompt: `You are a translator. The user's next message is the exact text to translate. Translate it from {{sourceLang}} to {{targetLang}}. Reply with nothing but the translated text\u2014no explanations, no "please provide" or meta-commentary.`,
  defaultSourceLang: "auto",
  defaultTargetLang: "en",
  pollIntervalMs: 1e3,
  maxAttempts: 3,
  timeoutMs: 2e4,
  maxChars: 4e3,
  extraHeadersRaw: "",
  debug: false
};
var TranslateBlockSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Translate Block Settings" });
    new import_obsidian.Setting(containerEl).setName("Debug").setDesc("Enable to print debug logs to the browser console (Developer Tools).").addToggle(
      (toggle) => {
        var _a;
        return toggle.setValue((_a = this.plugin.settings.debug) != null ? _a : false).onChange(async (value) => {
          this.plugin.settings.debug = value;
          await this.plugin.saveSettings();
        });
      }
    );
    new import_obsidian.Setting(containerEl).setName("Endpoint URL").setDesc("Full URL for the translation API endpoint (default: local Ollama at http://localhost:13434/api/chat).").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.endpointUrl).setValue(this.plugin.settings.endpointUrl).onChange(async (value) => {
        this.plugin.settings.endpointUrl = value.trim() || DEFAULT_SETTINGS.endpointUrl;
        await this.plugin.saveSettings();
      })
    );
    const modelList = parseModelList(
      this.plugin.settings.modelsRaw,
      this.plugin.settings.defaultModel
    );
    const defaultModel = resolveModel(modelList, this.plugin.settings.defaultModel);
    let defaultModelDropdown;
    new import_obsidian.Setting(containerEl).setName("Models").setDesc("Model names available in dropdowns, one per line.").setClass("setting-control-on-new-line").addTextArea((text) => {
      var _a;
      text.setPlaceholder("llama3\nmistral\ntranslategemma:27b").setValue((_a = this.plugin.settings.modelsRaw) != null ? _a : DEFAULT_SETTINGS.modelsRaw).onChange(async (value) => {
        this.plugin.settings.modelsRaw = value;
        const list = parseModelList(value, this.plugin.settings.defaultModel);
        this.plugin.settings.defaultModel = resolveModel(list, this.plugin.settings.defaultModel);
        await this.plugin.saveSettings();
        this.plugin.refreshWorkspaceModelOptions();
      });
      text.inputEl.addEventListener("blur", () => {
        if (!defaultModelDropdown) return;
        const list = parseModelList(
          this.plugin.settings.modelsRaw,
          this.plugin.settings.defaultModel
        );
        const selected = resolveModel(list, this.plugin.settings.defaultModel);
        defaultModelDropdown.selectEl.empty();
        for (const name of list) {
          defaultModelDropdown.addOption(name, name);
        }
        defaultModelDropdown.setValue(selected);
        this.plugin.settings.defaultModel = selected;
      });
    });
    new import_obsidian.Setting(containerEl).setName("Default model").setDesc("Model used when a block or panel does not override it.").addDropdown((dropdown) => {
      defaultModelDropdown = dropdown;
      for (const name of modelList) {
        dropdown.addOption(name, name);
      }
      dropdown.setValue(defaultModel).onChange(async (value) => {
        const list = parseModelList(
          this.plugin.settings.modelsRaw,
          this.plugin.settings.defaultModel
        );
        this.plugin.settings.defaultModel = resolveModel(list, value);
        await this.plugin.saveSettings();
        this.plugin.refreshWorkspaceModelOptions();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Default source language").setDesc("Language of the source text.").addDropdown((dropdown) => {
      for (const code of LANGUAGE_OPTIONS) {
        dropdown.addOption(code, code);
      }
      dropdown.setValue(
        resolveLanguage(this.plugin.settings.defaultSourceLang, DEFAULT_SETTINGS.defaultSourceLang)
      ).onChange(async (value) => {
        this.plugin.settings.defaultSourceLang = resolveLanguage(
          value,
          DEFAULT_SETTINGS.defaultSourceLang
        );
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Default target language").setDesc("Language to translate into.").addDropdown((dropdown) => {
      for (const code of LANGUAGE_OPTIONS) {
        dropdown.addOption(code, code);
      }
      dropdown.setValue(
        resolveLanguage(this.plugin.settings.defaultTargetLang, DEFAULT_SETTINGS.defaultTargetLang)
      ).onChange(async (value) => {
        this.plugin.settings.defaultTargetLang = resolveLanguage(
          value,
          DEFAULT_SETTINGS.defaultTargetLang
        );
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Poll interval (ms)").setDesc("Auto-translate polling interval in milliseconds. Minimum value is 500 ms.").addText(
      (text) => text.setPlaceholder(String(DEFAULT_SETTINGS.pollIntervalMs)).setValue(String(this.plugin.settings.pollIntervalMs)).onChange(async (value) => {
        const parsed = Number(value);
        const clamped = Number.isFinite(parsed) && parsed > 0 ? Math.max(MIN_POLL_INTERVAL_MS, Math.floor(parsed)) : DEFAULT_SETTINGS.pollIntervalMs;
        this.plugin.settings.pollIntervalMs = clamped;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max attempts").setDesc("Maximum number of retry attempts for a single translation job.").addText(
      (text) => text.setPlaceholder(String(DEFAULT_SETTINGS.maxAttempts)).setValue(String(this.plugin.settings.maxAttempts)).onChange(async (value) => {
        const parsed = Number(value);
        const next = Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : DEFAULT_SETTINGS.maxAttempts;
        this.plugin.settings.maxAttempts = next;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Request timeout (ms)").setDesc("Timeout for each translation request in milliseconds.").addText(
      (text) => text.setPlaceholder(String(DEFAULT_SETTINGS.timeoutMs)).setValue(String(this.plugin.settings.timeoutMs)).onChange(async (value) => {
        const parsed = Number(value);
        const next = Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : DEFAULT_SETTINGS.timeoutMs;
        this.plugin.settings.timeoutMs = next;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max block size (characters)").setDesc("Maximum source text length for auto-translate. Larger blocks require manual translation.").addText(
      (text) => text.setPlaceholder(String(DEFAULT_SETTINGS.maxChars)).setValue(String(this.plugin.settings.maxChars)).onChange(async (value) => {
        const parsed = Number(value);
        const next = Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : DEFAULT_SETTINGS.maxChars;
        this.plugin.settings.maxChars = next;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default prompt").setDesc("Prompt template for translation. You can use {{sourceLang}} and {{targetLang}} placeholders.").setClass("setting-control-on-new-line").addTextArea(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.defaultPrompt).setValue(this.plugin.settings.defaultPrompt).onChange(async (value) => {
        this.plugin.settings.defaultPrompt = value.trim() || DEFAULT_SETTINGS.defaultPrompt;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Extra headers").setDesc("Optional HTTP headers as `Key: Value`, one per line. Useful for API keys or custom auth.").setClass("setting-control-on-new-line").addTextArea(
      (text) => text.setPlaceholder("Authorization: Bearer YOUR_TOKEN").setValue(this.plugin.settings.extraHeadersRaw).onChange(async (value) => {
        this.plugin.settings.extraHeadersRaw = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/translation-backend.ts
var import_obsidian2 = require("obsidian");
function createDefaultBackend() {
  return new OllamaBackend();
}
function buildExtraHeaders(extraHeadersRaw) {
  const headers = {};
  const lines = extraHeadersRaw.split("\n");
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim();
    if (!key || !value) continue;
    headers[key] = value;
  }
  return headers;
}
function buildPromptTemplate(prompt, sourceLang, targetLang) {
  let result = prompt || DEFAULT_SETTINGS.defaultPrompt;
  const effectiveSource = sourceLang || DEFAULT_SETTINGS.defaultSourceLang;
  const effectiveTarget = targetLang || DEFAULT_SETTINGS.defaultTargetLang;
  result = result.replace(/{{sourceLang}}/g, effectiveSource);
  result = result.replace(/{{targetLang}}/g, effectiveTarget);
  return result;
}
function debugLog(options, ...args) {
  if (options.debug) {
    console.log("[translate-block]", ...args);
  }
}
var OllamaBackend = class {
  async translate(text, sourceLang, targetLang, options) {
    var _a;
    const url = (options.endpointUrl || DEFAULT_SETTINGS.endpointUrl).replace(/\/$/, "");
    debugLog(options, "POST \u2192", url);
    const systemPrompt = buildPromptTemplate(options.prompt, sourceLang, targetLang);
    const payload = JSON.stringify({
      model: options.model || DEFAULT_SETTINGS.defaultModel,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: text }
      ],
      stream: false
    });
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      contentType: "application/json",
      body: payload,
      headers: buildExtraHeaders(options.extraHeadersRaw),
      throw: false
    });
    debugLog(options, "Response status:", response.status);
    if (response.status < 200 || response.status >= 300) {
      throw new Error(`HTTP ${response.status}: ${response.text || "Unknown error"}`);
    }
    const data = response.json;
    const content = (_a = data.message) == null ? void 0 : _a.content;
    if (!content) {
      console.error("[translate-block] Unexpected response shape:", response.text);
      throw new Error("No content in translation response.");
    }
    return content.trim();
  }
};

// src/translate-panel-view.ts
var import_obsidian3 = require("obsidian");

// src/translate-workspace.ts
function mountTranslateWorkspace(parentEl, host, options) {
  const models = host.getModelList();
  const sourceLang = resolveLanguage(options.initialSourceLang, host.defaultSourceLang);
  const targetLang = resolveLanguage(options.initialTargetLang, host.defaultTargetLang);
  const model = resolveModel(models, options.initialModel || host.defaultModel);
  const prompt = options.prompt;
  const rootClasses = ["translate-block-container"];
  if (options.containerClass) {
    rootClasses.push(options.containerClass);
  }
  const container = parentEl.createDiv({ cls: rootClasses.join(" ") });
  const inputPanel = container.createDiv({ cls: "translate-block-input" });
  inputPanel.createEl("div", { text: "Input", cls: "translate-block-panel-label" });
  const inputArea = inputPanel.createEl("textarea", { cls: "translate-block-input-area" });
  inputArea.value = options.initialSourceText;
  inputArea.placeholder = "Content to translate\u2026";
  const resizeInput = () => {
    inputArea.style.height = "0";
    const newHeight = Math.max(120, inputArea.scrollHeight);
    inputArea.style.height = `${newHeight}px`;
  };
  requestAnimationFrame(() => resizeInput());
  const controlsBar = container.createDiv({ cls: "translate-block-controls" });
  const outputPanel = container.createDiv({ cls: "translate-block-output" });
  outputPanel.createEl("div", { text: "Output", cls: "translate-block-panel-label" });
  const outputContent = outputPanel.createDiv({ cls: "translate-block-output-content" });
  const statusEl = container.createDiv({ cls: "translate-block-status" });
  const state = {
    id: options.id,
    sourceLang,
    targetLang,
    model,
    prompt,
    sourceText: options.initialSourceText,
    lastSourceHash: null,
    inFlight: false,
    retryCount: 0,
    mode: "manual",
    outputEl: outputContent,
    statusEl
  };
  host.registerWorkspace(state);
  const syncStateFromInput = () => {
    state.sourceText = inputArea.value;
    state.lastSourceHash = null;
  };
  inputArea.addEventListener("input", () => {
    syncStateFromInput();
    resizeInput();
  });
  inputArea.addEventListener("change", () => syncStateFromInput());
  const sourceSelect = controlsBar.createEl("select");
  const targetSelect = controlsBar.createEl("select");
  populateLanguageSelect(sourceSelect, state.sourceLang);
  populateLanguageSelect(targetSelect, state.targetLang);
  sourceSelect.addEventListener("change", () => {
    state.sourceLang = sourceSelect.value || host.defaultSourceLang;
    state.lastSourceHash = null;
  });
  targetSelect.addEventListener("change", () => {
    state.targetLang = targetSelect.value || host.defaultTargetLang;
    state.lastSourceHash = null;
  });
  const modelSelect = controlsBar.createEl("select", { cls: "translate-block-model-select" });
  state.modelSelectEl = modelSelect;
  populateModelSelect(modelSelect, models, state.model);
  modelSelect.addEventListener("change", () => {
    state.model = resolveModel(host.getModelList(), modelSelect.value);
    state.lastSourceHash = null;
  });
  const translateButton = controlsBar.createEl("button", { text: "Translate" });
  translateButton.addEventListener("click", () => {
    void host.triggerManualTranslate(state.id);
  });
  if (options.onSaveToBlock) {
    const saveButton = controlsBar.createEl("button", { text: "Save to block" });
    saveButton.addEventListener("click", () => {
      var _a;
      (_a = options.onSaveToBlock) == null ? void 0 : _a.call(options);
    });
  }
  const autoLabel = controlsBar.createEl("label");
  const autoToggle = autoLabel.createEl("input", { type: "checkbox" });
  state.autoToggleEl = autoToggle;
  autoLabel.appendText(" Auto");
  autoToggle.checked = state.mode === "auto";
  autoToggle.addEventListener("change", () => {
    state.mode = autoToggle.checked ? "auto" : "manual";
    if (state.mode === "auto") {
      statusEl.setText("Auto mode enabled. Waiting for changes\u2026");
    } else {
      statusEl.setText("Manual mode. Click Translate to run.");
    }
  });
  if (state.mode === "auto") {
    statusEl.setText("Auto mode enabled. Waiting for changes\u2026");
  } else {
    statusEl.setText("Manual mode. Click Translate to run.");
  }
  const handle = {
    id: options.id,
    getState: () => state,
    destroy: () => {
      container.remove();
    },
    refreshModelOptions: () => {
      const list = host.getModelList();
      state.model = resolveModel(list, state.model);
      populateModelSelect(modelSelect, list, state.model);
    }
  };
  return handle;
}

// src/translate-panel-view.ts
var VIEW_TYPE_TRANSLATE_PANEL = "translate-panel";
var TranslatePanelView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.panelWorkspaceId = `translate-panel:${Date.now().toString(36)}`;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TRANSLATE_PANEL;
  }
  getDisplayText() {
    return "Translate";
  }
  getIcon() {
    return "languages";
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("translate-panel-view");
    this.workspaceHandle = mountTranslateWorkspace(contentEl, this.plugin.getWorkspaceHost(), {
      id: this.panelWorkspaceId,
      initialSourceText: "",
      initialSourceLang: this.plugin.settings.defaultSourceLang,
      initialTargetLang: this.plugin.settings.defaultTargetLang,
      initialModel: this.plugin.settings.defaultModel,
      prompt: this.plugin.settings.defaultPrompt,
      containerClass: "translate-panel-container"
    });
  }
  async onClose() {
    if (this.workspaceHandle) {
      this.plugin.unregisterWorkspace(this.workspaceHandle.id);
      this.workspaceHandle.destroy();
      this.workspaceHandle = void 0;
    }
    this.contentEl.empty();
  }
  refreshModelOptions() {
    var _a;
    (_a = this.workspaceHandle) == null ? void 0 : _a.refreshModelOptions();
  }
};

// src/main.ts
var _TranslateBlockPlugin = class _TranslateBlockPlugin extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.workspaceStates = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.backend = createDefaultBackend();
    this.registerView(VIEW_TYPE_TRANSLATE_PANEL, (leaf) => new TranslatePanelView(leaf, this));
    this.addRibbonIcon("languages", "Open Translate Panel", () => {
      void this.activateTranslatePanel();
    });
    this.addCommand({
      id: "open-translate-panel",
      name: "Open Translate Panel",
      callback: () => {
        void this.activateTranslatePanel();
      }
    });
    this.registerMarkdownCodeBlockProcessor("translate-block", (source, el, ctx) => {
      this.processTranslateBlock(source, el, ctx);
    });
    this.addSettingTab(new TranslateBlockSettingTab(this.app, this));
    this.startPolling();
  }
  onunload() {
    if (this.pollIntervalId !== void 0) {
      window.clearInterval(this.pollIntervalId);
    }
    this.workspaceStates.clear();
  }
  /** Narrow API for TranslateWorkspace mounts (panel + blocks). */
  getWorkspaceHost() {
    return {
      getModelList: () => this.getModelList(),
      defaultSourceLang: this.settings.defaultSourceLang,
      defaultTargetLang: this.settings.defaultTargetLang,
      defaultModel: this.settings.defaultModel,
      isValidLang: (value) => this.isValidLang(value),
      registerWorkspace: (state) => this.registerWorkspace(state),
      triggerManualTranslate: (id) => this.triggerManualTranslate(id)
    };
  }
  getModelList() {
    return parseModelList(this.settings.modelsRaw, this.settings.defaultModel);
  }
  registerWorkspace(incoming) {
    const existing = this.workspaceStates.get(incoming.id);
    if (existing) {
      incoming.mode = existing.mode;
      incoming.inFlight = existing.inFlight;
      incoming.lastSourceHash = existing.lastSourceHash;
      incoming.retryCount = existing.retryCount;
      incoming.lastError = existing.lastError;
      incoming.lastUpdatedAt = existing.lastUpdatedAt;
    }
    this.workspaceStates.set(incoming.id, incoming);
  }
  unregisterWorkspace(id) {
    this.workspaceStates.delete(id);
  }
  refreshWorkspaceModelOptions() {
    const list = this.getModelList();
    for (const state of this.workspaceStates.values()) {
      state.model = resolveModel(list, state.model);
      if (state.modelSelectEl) {
        populateModelSelect(state.modelSelectEl, list, state.model);
      }
    }
  }
  async activateTranslatePanel() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_TRANSLATE_PANEL);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const rightLeaf = workspace.getRightLeaf(false);
    const leaf = rightLeaf != null ? rightLeaf : workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_TRANSLATE_PANEL, active: true });
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    var _a, _b;
    const data = await this.loadData();
    const merged = Object.assign({}, DEFAULT_SETTINGS, data != null ? data : {});
    if (!merged.pollIntervalMs || merged.pollIntervalMs < MIN_POLL_INTERVAL_MS) {
      merged.pollIntervalMs = Math.max(
        MIN_POLL_INTERVAL_MS,
        merged.pollIntervalMs || DEFAULT_SETTINGS.pollIntervalMs
      );
    }
    if (!((_a = merged.modelsRaw) == null ? void 0 : _a.trim())) {
      merged.modelsRaw = ((_b = merged.defaultModel) == null ? void 0 : _b.trim()) || DEFAULT_SETTINGS.modelsRaw;
    }
    const list = parseModelList(merged.modelsRaw, merged.defaultModel);
    merged.defaultModel = resolveModel(list, merged.defaultModel);
    merged.defaultSourceLang = resolveLanguage(
      merged.defaultSourceLang,
      DEFAULT_SETTINGS.defaultSourceLang
    );
    merged.defaultTargetLang = resolveLanguage(
      merged.defaultTargetLang,
      DEFAULT_SETTINGS.defaultTargetLang
    );
    this.settings = merged;
  }
  async saveSettings() {
    if (!this.settings.pollIntervalMs || this.settings.pollIntervalMs < MIN_POLL_INTERVAL_MS) {
      this.settings.pollIntervalMs = Math.max(
        MIN_POLL_INTERVAL_MS,
        this.settings.pollIntervalMs || DEFAULT_SETTINGS.pollIntervalMs
      );
    }
    const list = parseModelList(this.settings.modelsRaw, this.settings.defaultModel);
    this.settings.defaultModel = resolveModel(list, this.settings.defaultModel);
    this.settings.defaultSourceLang = resolveLanguage(
      this.settings.defaultSourceLang,
      DEFAULT_SETTINGS.defaultSourceLang
    );
    this.settings.defaultTargetLang = resolveLanguage(
      this.settings.defaultTargetLang,
      DEFAULT_SETTINGS.defaultTargetLang
    );
    await this.saveData(this.settings);
  }
  startPolling() {
    const interval = this.settings.pollIntervalMs || DEFAULT_SETTINGS.pollIntervalMs;
    const effectiveInterval = Math.max(MIN_POLL_INTERVAL_MS, interval);
    this.pollIntervalId = window.setInterval(() => {
      void this.pollWorkspaces();
    }, effectiveInterval);
    this.registerInterval(this.pollIntervalId);
  }
  processTranslateBlock(source, el, ctx) {
    var _a;
    const decodedSource = this.decodeBlockContent(source);
    const blockId = this.getBlockId(ctx, el);
    const info = ctx.getSectionInfo(el);
    const fenceConfig = this.parseFenceConfig(ctx, el);
    const models = this.getModelList();
    el.empty();
    const onSaveToBlock = info && info.lineStart != null && info.lineEnd != null ? () => {
      var _a2, _b;
      const lines = info.text.split("\n");
      const fenceLine = (_a2 = lines.find((line) => line.trim().startsWith("```translate-block"))) != null ? _a2 : "```translate-block";
      const state = this.workspaceStates.get(blockId);
      const content = (_b = state == null ? void 0 : state.sourceText) != null ? _b : decodedSource;
      void this.updateCodeBlockInFile(
        ctx.sourcePath,
        info.lineStart,
        info.lineEnd,
        fenceLine,
        content
      );
    } : void 0;
    mountTranslateWorkspace(el, this.getWorkspaceHost(), {
      id: blockId,
      initialSourceText: decodedSource,
      initialSourceLang: fenceConfig.sourceLang || this.settings.defaultSourceLang,
      initialTargetLang: fenceConfig.targetLang || this.settings.defaultTargetLang,
      initialModel: resolveModel(models, fenceConfig.model || this.settings.defaultModel),
      prompt: ((_a = fenceConfig.prompt) == null ? void 0 : _a.trim()) || this.settings.defaultPrompt,
      onSaveToBlock
    });
  }
  parseFenceConfig(ctx, el) {
    const info = ctx.getSectionInfo(el);
    if (!info || !info.text) {
      return {};
    }
    const lines = info.text.split("\n");
    const fenceLine = lines.find((line) => line.trim().startsWith("```translate-block"));
    if (!fenceLine) {
      return {};
    }
    const trimmed = fenceLine.trim();
    const withoutTicks = trimmed.startsWith("```") ? trimmed.slice(3).trim() : trimmed;
    const parts = withoutTicks.split(/\s+/);
    const [, ...rest] = parts;
    const result = {};
    for (const token of rest) {
      const eqIndex = token.indexOf("=");
      if (eqIndex === -1) continue;
      const key = token.slice(0, eqIndex).trim();
      const value = token.slice(eqIndex + 1).trim();
      if (!key || !value) continue;
      switch (key) {
        case "source":
        case "sourceLang":
          if (this.isValidLang(value)) {
            result.sourceLang = value;
          }
          break;
        case "target":
        case "targetLang":
          if (this.isValidLang(value)) {
            result.targetLang = value;
          }
          break;
        case "model":
          result.model = value;
          break;
        case "prompt":
          result.prompt = value;
          break;
        default:
          break;
      }
    }
    return result;
  }
  getBlockId(ctx, el) {
    const info = ctx.getSectionInfo(el);
    if (info) {
      return `${ctx.sourcePath}:${info.lineStart}-${info.lineEnd}`;
    }
    return `${ctx.sourcePath}:${Math.random().toString(36).slice(2)}`;
  }
  /**
   * Encodes block content for saving: appends U+200B to any line that could be
   * interpreted as a closing fence (optional leading/trailing whitespace + 3+ backticks).
   */
  encodeBlockContentForSave(content) {
    const re = /^\s*`{3,}\s*$/;
    return content.split(/\r?\n/).map((line) => re.test(line) ? line + _TranslateBlockPlugin.FENCE_ESCAPE : line).join("\n");
  }
  /**
   * Decodes block content when loading: removes the trailing U+200B from lines
   * we encoded (fence-like line + U+200B), restoring the original fence line.
   */
  decodeBlockContent(source) {
    const re = /^(\s*`{3,}\s*)\u200B$/;
    return source.split(/\r?\n/).map((line) => line.replace(re, "$1")).join("\n");
  }
  /**
   * Updates the code block content in the note file.
   * lineStart/lineEnd are 0-based (inclusive) indices into the file's line array.
   */
  async updateCodeBlockInFile(sourcePath, lineStart, lineEnd, fenceLine, newContent) {
    const file = this.app.vault.getFileByPath(sourcePath);
    if (!file) return;
    try {
      const content = await this.app.vault.read(file);
      const lines = content.split(/\r?\n/);
      const before = lines.slice(0, lineStart);
      const after = lines.slice(lineEnd + 1);
      const encoded = this.encodeBlockContentForSave(newContent);
      const newBlockLines = [fenceLine, ...encoded.split(/\r?\n/), "```"];
      const newFileContent = [...before, ...newBlockLines, ...after].join("\n");
      await this.app.vault.modify(file, newFileContent);
    } catch (e) {
      new import_obsidian4.Notice(
        "Translate Block: could not update note. " + (e instanceof Error ? e.message : String(e))
      );
    }
  }
  async pollWorkspaces() {
    if (!this.backend) {
      this.backend = createDefaultBackend();
    }
    for (const state of this.workspaceStates.values()) {
      if (state.mode !== "auto") continue;
      if (state.inFlight) continue;
      if (state.sourceText.length > this.settings.maxChars) {
        state.statusEl.setText(
          `Block too large for auto-translate (>${this.settings.maxChars} chars). Use manual Translate.`
        );
        continue;
      }
      const hash = this.computeHash(state);
      if (state.lastSourceHash === hash) {
        continue;
      }
      await this.runTranslationJob(state.id);
    }
  }
  computeHash(state) {
    const key = [state.sourceText, state.sourceLang, state.targetLang, state.model, state.prompt].join(
      "||"
    );
    let hash = 0;
    for (let i = 0; i < key.length; i += 1) {
      hash = (hash << 5) - hash + key.charCodeAt(i);
      hash |= 0;
    }
    return String(hash);
  }
  isValidLang(value) {
    const v = value.trim();
    if (!v) return false;
    return /^[a-zA-Z-]+$/.test(v);
  }
  async triggerManualTranslate(blockId) {
    await this.runTranslationJob(blockId);
  }
  async runTranslationJob(blockId) {
    if (!this.backend) {
      this.backend = createDefaultBackend();
    }
    const state = this.workspaceStates.get(blockId);
    if (!state) return;
    if (state.inFlight) {
      return;
    }
    if (state.sourceText.length === 0) {
      state.outputEl.empty();
      state.statusEl.setText("No source text to translate.");
      return;
    }
    if (state.sourceText.length > this.settings.maxChars) {
      state.statusEl.setText(
        `Block too large (${state.sourceText.length} chars). Reduce size or increase max block size in settings.`
      );
      return;
    }
    state.inFlight = true;
    state.lastError = void 0;
    state.statusEl.setText("Translating\u2026");
    const hash = this.computeHash(state);
    const maxAttempts = this.settings.maxAttempts;
    let attempt = 0;
    let lastErrorMessage;
    const model = resolveModel(this.getModelList(), state.model);
    while (attempt < maxAttempts) {
      attempt += 1;
      state.retryCount = attempt;
      try {
        const translated = await this.backend.translate(
          state.sourceText,
          state.sourceLang,
          state.targetLang,
          {
            endpointUrl: this.settings.endpointUrl,
            model,
            timeoutMs: this.settings.timeoutMs,
            prompt: state.prompt,
            extraHeadersRaw: this.settings.extraHeadersRaw,
            debug: this.settings.debug
          }
        );
        state.outputEl.empty();
        const pre = state.outputEl.createEl("pre", {
          text: translated,
          cls: "translate-block-output-pre"
        });
        pre.setAttribute("contenteditable", "false");
        state.lastSourceHash = hash;
        state.retryCount = 0;
        state.inFlight = false;
        state.lastUpdatedAt = Date.now();
        state.statusEl.setText("Translated successfully.");
        return;
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        lastErrorMessage = message;
        const isSoftError = this.isSoftErrorMessage(message);
        if (!isSoftError || attempt >= maxAttempts) {
          break;
        }
        await new Promise((resolve) => window.setTimeout(resolve, 300));
      }
    }
    state.inFlight = false;
    state.lastError = lastErrorMessage;
    state.lastSourceHash = hash;
    state.statusEl.setText(
      `Translation failed after ${Math.max(1, state.retryCount)} attempt(s). Last error: ${lastErrorMessage != null ? lastErrorMessage : "Unknown error"}`
    );
    new import_obsidian4.Notice("Translate Block error. See block status for details.");
  }
  isSoftErrorMessage(message) {
    const lower = message.toLowerCase();
    if (lower.includes("timeout") || lower.includes("network")) return true;
    if (lower.includes("502") || lower.includes("503") || lower.includes("504") || lower.includes("500"))
      return true;
    return false;
  }
};
/** Zero-width space used to escape fence-like lines so they do not close the code block. */
_TranslateBlockPlugin.FENCE_ESCAPE = "\u200B";
var TranslateBlockPlugin = _TranslateBlockPlugin;
